{{- if .Values.consumer.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vita-consumer-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "services", "persistentvolumeclaims", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vita-consumer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vita-consumer-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.consumer.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
