{{- if .Values.consumer.enabled -}}
{{- if .Values.consumer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.consumer.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: vita-consumer
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
