{{- if .Values.consumer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-consumer
  labels:
    app.kubernetes.io/name: vita-consumer
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.consumer.service.type }}
  ports:
    - port: {{ .Values.consumer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vita-consumer
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
